export const doctors = [
  {
    id: 1,
    name: "Dr. Ayesha Rahman",
    profilePhoto: "https://i.ibb.co/qgXXYNL/doctor-1.jpg",
    qualification: "MBBS, FCPS (Medicine)",
    designation: "Consultant Physician",
    address: "Square Hospital, Dhaka",
    apointmentFee: "৳1500",
  },
  {
    id: 2,
    name: "Dr. Tahmid Hossain",
    profilePhoto: "https://i.ibb.co/JHcDPzv/doctor-2.jpg",
    qualification: "MBBS, MS (Surgery)",
    designation: "General Surgeon",
    address: "United Hospital, Dhaka",
    apointmentFee: "৳2000",
  },
  {
    id: 3,
    name: "Dr. Shirin Akter",
    profilePhoto: "https://i.ibb.co/9sRy7Ym/doctor-3.jpg",
    qualification: "MBBS, DGO, MCPS (Gynae)",
    designation: "Gynecologist & Obstetrician",
    address: "Labaid Hospital, Dhanmondi",
    apointmentFee: "৳1800",
  },
  {
    id: 4,
    name: "Dr. Mahmud Hasan",
    profilePhoto: "https://i.ibb.co/KsmMLT8/doctor-4.jpg",
    qualification: "MBBS, FCPS (Cardiology)",
    designation: "Cardiologist",
    address: "National Heart Foundation, Dhaka",
    apointmentFee: "৳2500",
  },
  {
    id: 5,
    name: "Dr. Nusrat Jahan",
    profilePhoto: "https://i.ibb.co/vJtCxmb/doctor-5.jpg",
    qualification: "MBBS, MD (Neurology)",
    designation: "Neurologist",
    address: "Evercare Hospital, Dhaka",
    apointmentFee: "৳2200",
  },
  {
    id: 6,
    name: "Dr. Rezaul Karim",
    profilePhoto: "https://i.ibb.co/S5h8Z9s/doctor-6.jpg",
    qualification: "MBBS, MS (Orthopedics)",
    designation: "Orthopedic Surgeon",
    address: "Apollo Hospitals, Dhaka",
    apointmentFee: "৳2000",
  },
  {
    id: 7,
    name: "Dr. Fatema Noor",
    profilePhoto: "https://i.ibb.co/nRcZXKT/doctor-7.jpg",
    qualification: "MBBS, FCPS (Dermatology)",
    designation: "Dermatologist",
    address: "Popular Diagnostic Center, Dhaka",
    apointmentFee: "৳1600",
  },
  {
    id: 8,
    name: "Dr. Imran Chowdhury",
    profilePhoto: "https://i.ibb.co/D5SZGNT/doctor-8.jpg",
    qualification: "MBBS, MD (Pediatrics)",
    designation: "Child Specialist",
    address: "Ibn Sina Hospital, Dhanmondi",
    apointmentFee: "৳1500",
  },
  {
    id: 9,
    name: "Dr. Nafisa Sultana",
    profilePhoto: "https://i.ibb.co/3C6WrP6/doctor-9.jpg",
    qualification: "MBBS, FCPS (ENT)",
    designation: "ENT Specialist",
    address: "Green Life Hospital, Dhaka",
    apointmentFee: "৳1700",
  },
  {
    id: 10,
    name: "Dr. Asif Mahmud",
    profilePhoto: "https://i.ibb.co/GJBC6Sv/doctor-10.jpg",
    qualification: "MBBS, MD (Psychiatry)",
    designation: "Psychiatrist",
    address: "Bangabandhu Sheikh Mujib Medical University",
    apointmentFee: "৳1900",
  },
];
